name: Destroy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * FRI'

jobs:
  destroy-terraform-dev:
    secrets: inherit
    permissions:
      issues: write
      contents: read
      pull-requests: write
    uses: guidion-digital/terrappy/.github/workflows/tfc-destroy-enterprise.yaml@v1
    with:
      environment_name: "dev"
      working_directory: ./examples/test_app

  destroy-terraform-acc:
    secrets: inherit
    permissions:
      issues: write
      contents: read
      pull-requests: write
    uses: guidion-digital/terrappy/.github/workflows/tfc-destroy-enterprise.yaml@v1
    with:
      environment_name: "acc"
      working_directory: ./examples/test_app
